### ISSUE TITLE
Fix issue with primary keys

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#908]
Currently `list-sql-schema` script generates `pk` type with original column name, but in Spinta `pk` type can only be used with `_id`. So instead, an original type should be used for primary keys and an `_id` should be generated like this:

```yaml
_id:
  type: pk
  source: BYL_ID
byl_id:
  type: integer
  source: BYL_ID
```
