### ISSUE TITLE
Generate manifest YAM files form new inventory table format

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#915]
Update an existing [csv-to-manifest](https://gitlab.com/atviriduomenys/manifest/-/blob/master/scripts/csv-to-manifest) script to read data from an update inventory table format.

Inventory table will be given as a CSV file, here is an example inventory table in CSV format:

```
dataset,resource,base,model,property,source,prepare,type,ref,level,access,title,description
datasets/example/cities,,,,,,,,,,,,
,db,,,,,,sql,,,,,
,,,,,,,,,,,,
,,,cities,CITY,,,id,,,,,
,,,,id,ID,,integer,,4,private,,
,,,,name,NAME,,string,,3,open,,
```

Example output, that should be generated from that CSV file:

File `datasets/example/cities.dataset.yml`:

```yaml
type: dataset
name: datasets/example/cities
resources:
  db:
    type: sql
```

File `datasets/example/cities/cities.yml`:

```yaml
type: model
name: datasets/example/cities/cities
pull:
  dataset: datasets/example/cities
  resource: countries
  source: CITY
  pk: id
properties:
  id:
    type: integer
    pull: ID
    level: 4
    access: private
  name:
    type: string
    pull: NAME
    level: 3
    access: open
```

More information about CSV and YAML file structure can be found here: https://atviriduomenys.readthedocs.io/

Script should called like this:

    csv-to-manifest path/to/file.csv path/to/manifest/directory

Script should read given `path/to/file.csv` file, and create directories and files under `path/to/manifest/directory`.

For command line argument handling use [click](https://click.palletsprojects.com/en/7.x/).

For reading CSV file, use build-in [csv](https://docs.python.org/3/library/csv.html#csv.DictReader) module.

For path manipulation use build-in [pathlib](https://docs.python.org/3/library/pathlib.html) module.

Write tests using [py.test](https://docs.pytest.org/), for testing created files and directories use [tmpdir](https://docs.pytest.org/en/latest/tmpdir.html#the-tmpdir-fixture) fixture.

There is already a script, that same thing, except it uses an old inventory and manifest formats. Inventory and manifest formats has been changes, so this script needs to be updated.

Files that should be updated:

- [scripts/csv-to-manifest](https://gitlab.com/atviriduomenys/manifest/-/blob/master/scripts/csv-to-manifest) - script entry point, currently this script accepts only one command line argument, it should accept two arguments, csv file and manifest directory. Currently manifest directory is taken from `context`. `context` is no longer needed, instead of `context` pass manifest path directly to `update_manifest_files` function.

- [lodam/services/gsheets.py](https://gitlab.com/atviriduomenys/manifest/-/blob/master/lodam/services/gsheets.py#L67) in this file, you need to update `update_manifest_files` function, replace `context` argument with a path to manifest argument and updated whole function to work with new inventory table and manifest files.

- [tests/scripts/test_gsheetstomanifest.py](https://gitlab.com/atviriduomenys/manifest/-/blob/master/tests/scripts/test_gsheetstomanifest.py) - update tests.

You can run tests like this:

    env/bin/by.test -vvx --tb=native tests/scripts/test_gsheetstomanifest.py

Create a new pull request, once you get to a working solution.
